service: "softtek-backend"

frameworkVersion: "4"

package:
  individually: true

custom:
  dev:
    BASE_URL_API_SWAPI: "https://swapi.py4e.com"
    BASE_URL_API_POKEAPI: "https://pokeapi.co"
    region: us-east-1
    infraName: softtek-infra-dev
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ["aws-sdk", "merged-layer"]
    target: node20
    watch:
      ignore: ["layers"]
    define:
      require.resolve: undefined
    platform: node
    concurrency: 10
  infra: ${self:custom.${opt:stage}.infraName}

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 30
  httpApi:
    cors:
      allowedOrigins: "*"
      allowedHeaders:
        - Content-Type
        - Authorization
        - X-Auth-Token
        - X-Data-Source
      allowedMethods:
        - OPTIONS
        - GET
        - POST
      maxAge: 6000 # In seconds
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  tracing:
    lambda: true
    apiGateway: true
  environment:
    region: ${self:custom.${opt:stage}.region}
    BASE_URL_API_SWAPI: ${self:custom.${opt:stage}.BASE_URL_API_SWAPI}
    BASE_URL_API_POKEAPI: ${self:custom.${opt:stage}.BASE_URL_API_POKEAPI}
    MERGED_TABLE_NAME:
      Fn::ImportValue: ${self:custom.infra}-MergedTableName
    POKEMON_TABLE_NAME:
      Fn::ImportValue: ${self:custom.infra}-PokemonTableName
    HISTORY_TABLE_NAME:
      Fn::ImportValue: ${self:custom.infra}-HistoryTableName
    SEARCHED_TOPIC_ARN: 
      Fn::ImportValue: ${self:custom.infra}-NotifySearchedTopic
    REDIS_HOST: "sor1koyi0fbimm2e-001.stinj1.0001.use1.cache.amazonaws.com:6379"
      # Fn::ImportValue: ${self:custom.infra}-RedisClusterEndpoint 

layers:
  Merged:
    path: layers/merged-layer/dist
    description: "Layer for merged star wars and pokemon"
    compatibleRuntimes:
      - nodejs20.x

functions:
  - ${file(./src/functions/getMerged/index.yml)}
  - ${file(./src/functions/postMerged/index.yml)}
  - ${file(./src/functions/getHistory/index.yml)}
  - ${file(./src/functions/snsHistory/index.yml)}