service: "sofftek-aws-backend"

frameworkVersion: "4"

package:
  individually: true

custom:
  dev:
    BASE_URL_API_SWAPI: "https://swapi.py4e.com"
    BASE_URL_API_POKEAPI: "https://pokeapi.co"
    region: us-east-1
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ["aws-sdk", "merged-layer"]
    target: node20
    watch:
      ignore: ["layers"]
    define:
      require.resolve: undefined
    platform: node
    concurrency: 10

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 30
  httpApi:
    cors:
      allowedOrigins: "*"
      allowedHeaders:
        - Content-Type
        - Authorization
        - X-Auth-Token
        - X-Data-Source
      allowedMethods:
        - OPTIONS
        - GET
      maxAge: 6000 # In seconds
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    region: ${self:custom.${opt:stage}.region}
    BASE_URL_API_SWAPI: ${self:custom.${opt:stage}.BASE_URL_API_SWAPI}
    BASE_URL_API_POKEAPI: ${self:custom.${opt:stage}.BASE_URL_API_POKEAPI}

layers:
  Merged:
    path: layers/merged-layer/dist
    description: "Layer for merged star wars and pokemon"
    compatibleRuntimes:
      - nodejs20.x

functions:
  - ${file(./src/functions/getMerged/index.yml)}
  - ${file(./src/functions/postMerged/index.yml)}
  - ${file(./src/functions/getHistory/index.yml)}