Resources:
  RedisCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      CacheNodeType: cache.t3.micro
      Engine: redis
      NumCacheNodes: 1
      CacheSubnetGroupName: { Ref: CacheSubnetGroup }
      VpcSecurityGroupIds:
        - { Ref: LambdaSecurityGroup }