Resources:
  RedisReplicationGroup:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      ReplicationGroupDescription: "Redis replication group"
      AutomaticFailoverEnabled: true
      Engine: redis
      CacheNodeType: cache.t3.micro
      NumCacheClusters: 2