Resources:
  HistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.historyTableName}
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: requesterId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: requesterId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST