Resources:
  ProviderRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      RoleName: provider-role-${opt:stage}
      ManagedPolicyArns:
        - { Ref: LogsCloudWatch }
        - { Ref: AdminInitiateAuth}